consul_agent:
    container_name: consul_agent
    image: cjongseok/consul
    restart: always
    expose: 
            - "8300"
            - "8301"
            - "8301/udp"
            - "8302"
            - "8302/udp"
            - "8400"
            - "8500"
            - "53/udp"
    ports:
        - "8300:8300"
        - "8301:8301"
        - "8301:8301/udp"
        - "8302:8302"
        - "8302:8302/udp"
        - "8400:8400"
        - "8500:8500"
        - "53:53/udp"
    environment:    
        # Below env variables are automatically allocated by consul_env.sh 
        - DOCKER_HOST_DNS_SERVER=
        ##################################################################
    command: aws-agent -join consul.infra.com 

registrator:
    container_name: consul-registrator
    image: gliderlabs/registrator
    restart: always
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
    links:
        - consul_agent:consul
    command: consul://consul:8500
